# Copyright 2017-2019 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
apiVersion: v1
kind: ConfigMap
metadata:
  name: wkldcontroller-config
  labels:
    app: auction
    tier: driver
    type: controller
    impl: wkldcontroller
data: 
  PORT: "80"
  JVMOPTS: "-Xmx6g -Xms6g -XX:+AlwaysPreTouch"
  WORKLOADNUM: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wkldcontroller
  labels:
    app: auction
    tier: driver
    type: controller
    impl: wkldcontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction
      tier: driver
      type: controller
      impl: wkldcontroller
  template:
    metadata:
      name: wkldcontroller
      labels:
        app: auction
        tier: driver
        type: controller
        impl: wkldcontroller
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: wvrole
                operator: NotIn
                values:
                - sut
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: wvrole
                operator: In
                values:
                - driver
      containers:
      - image: repository/weathervane-auctionworkloaddriver:2.0.0
        name: wkldcontroller
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: wkldcontroller-config
        ports: 
        - containerPort: 80
          name: wklddriverport
          protocol: TCP
        - containerPort: 9090
          name: jmxport
          protocol: TCP
        resources:
          requests:
            cpu: 1
            memory: 2Gi
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - 'jps | grep -Eq JarLauncher'
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - 'curl -s http://127.0.0.1:80/driver/up | grep -Eq true'
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: wkldcontroller
  labels:
    app: auction
    tier: driver
    type: controller
    impl: wkldcontroller
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: wklddriverport
  - port: 9090
    name: jmxport
  selector:
    app: auction
    tier: driver
    type: controller
    impl: wkldcontroller