apiVersion: v1
kind: ConfigMap
metadata:
  name: wklddriver-config
  labels:
    app: auction
    tier: driver
    type: node
data: 
  PORT: "7500"
  JVMOPTS: "-Xmx6g -Xms6g -XX:+AlwaysPreTouch"
  WORKLOADNUM: "1"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wklddriver
spec:
  serviceName: wklddriver
  selector:
    matchLabels:
      app: auction
      tier: driver
      type: node
  replicas: 1
  template:
    metadata:
      name: wklddriver
      labels:
        app: auction
        tier: driver
        type: node
    spec:
      containers:
      - image: hrosenbe/weathervane-auctionworkloaddriver:2.0.0
        name: wklddriver
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: wklddriver-config
        ports: 
        - containerPort: 7500
          name: wklddriverport
          protocol: TCP
        resources:
          requests:
            cpu: 1
            memory: 6Gi
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - 'jps | grep -Eq jar'
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - 'curl -s http://127.0.0.1:7500/run/up | grep -Eq true'
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: wklddriver
  labels:
    app: auction
    tier: driver
    type: node
spec:
  clusterIP: None
  ports:
  - port: 7500
    name: wklddriverport
  selector:
    app: auction
    tier: driver
    type: node