apiVersion: v1
kind: ConfigMap
metadata:
  name: auctionbidservice-config
  labels:
    app: auction
    tier: backend
    type: auctionBidServer
    impl: auctionbidservice
data: 
  TOMCAT_USE_TLS: "0"
  TOMCAT_JVMOPTS: "-Xmx6G -Xms6G -XX:+AlwaysPreTouch -XX:+PreserveFramePointer  -Dspring.profiles.active=postgresql,ehcache,imagesInMongo,singleMongo,singleRabbit,bidService  -DAUTHTOKENCACHESIZE=2000 -DACTIVEAUCTIONCACHESIZE=134  -DAUCTIONREPRESENTATIONCACHESIZE=134  -DIMAGEINFOCACHESIZE=6700 -DITEMSFORAUCTIONCACHESIZE=134  -DITEMCACHESIZE=1340  -DAUTHTOKENCACHEMODE=REPLICATED -DZOOKEEPERCONNECTIONSTRING=zookeeper:2181  -DITEMTHUMBNAILIMAGECACHESIZE=67  -DITEMPREVIEWIMAGECACHESIZE=1  -DITEMFULLIMAGECACHESIZE=1  -DRANDOMIZEIMAGES=true  -DHIGHBIDQUEUECONCURRENCY=2  -DNEWBIDQUEUECONCURRENCY=2  -DIMAGEWRITERTHREADS=1  -DUSEIMAGEWRITERTHREADS=true  -DNUMCLIENTUPDATETHREADS=2  -DNUMAUCTIONEERTHREADS=2  -DRABBITMQ_HOST=rabbitmq -DRABBITMQ_PORT=5672  -DMONGODB_HOST=mongodb -DMONGODB_PORT=27017  -DDBHOSTNAME=postgresql -DDBPORT=5432  -XX:CompileThreshold=2000  -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Xloggc:/opt/apache-tomcat-auction1/logs/gc.log  -DnodeNumber=1 "
  TOMCAT_SHUTDOWN_PORT: "8005"
  TOMCAT_CONNECTIONS: "5000"
  TOMCAT_THREADS: "96"
  TOMCAT_HTTPS_PORT: "8443"
  TOMCAT_JDBC_CONNECTIONS: "98"
  TOMCAT_DB_IMPL: "postgresql"
  TOMCAT_DB_HOSTNAME: "postgresql"
  TOMCAT_JDBC_MAXIDLE: "26"
  TOMCAT_HTTP_PORT: "8080"
  TOMCAT_DB_PORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auctionbidservice
  labels:
    app: auction
    tier: backend
    type: auctionBidServer
    impl: auctionbidservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction
      tier: backend
      type: auctionBidServer
      impl: auctionbidservice
  template:
    metadata:
      name: auctionbidservice
      labels:
        app: auction
        tier: backend
        type: auctionBidServer
        impl: auctionbidservice
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: wvrole
                operator: NotIn
                values:
                - driver
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: wvrole
                operator: In
                values:
                - sut
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: wvauctionw1i1
                operator: Exists
      containers:
      - image: repository/weathervane-auctionbidservice:1.2.0
        name: auctionbidservice
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: auctionbidservice-config
        ports: 
        - containerPort: 8080
          name: httpport
          protocol: TCP
        - containerPort: 8443
          name: httpsport
          protocol: TCP
        - containerPort: 9090
          name: jmxport
          protocol: TCP
        resources:
          requests:
            cpu: 1
            memory: 8Gi
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - 'jps | grep -Eq Bootstrap'
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - 'curl -s http://127.0.0.1:8080/auction/healthCheck | grep -Eq alive'
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: auctionbidservice
  labels:
    app: auction
    tier: backend
    type: auctionBidServer
    impl: auctionbidservice
spec:
  type: NodePort
  ports:
  - port: 8080
    name: httpport
  - port: 8443
    name: httpsport
  - port: 9090
    name: jmxport
  selector:
    app: auction
    tier: backend
    type: auctionBidServer
    impl: auctionbidservice