apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data: 
  WORKERCONNECTIONS : 100
  PERSERVERCONNECTIONS: 25000
  KEEPALIVETIMEOUT: 120
  MAXKEEPALIVEREQUESTS: 1000
  IMAGESTORETYPE: "mongodb"
  HTTPPORT: 9080
  HTTPSPORT: 9443
  APPSERVERS: "tomcat:8080"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      name: nginx
      labels:
        app: auction
        tier: web
        impl: nginx
    spec:
      containers:
      - image: hrosenbe/weathervane-nginx:1.1.0
        name: nginx
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: nginx-config
        ports: 
        - containerPort: 9080
          name: httpport
          protocol: TCP
        - containerPort: 9443
          name: httpsport
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - port: 9080
    name: httpport
  - port: 9443
    name: httpsport
  selector:
    app: auction
    tier: app
    impl: nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
spec:
  rules:
  - host: www.weathervane
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 9080