apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: auction
    tier: backend
    type: webServer
    impl: nginx
data: 
  WORKERCONNECTIONS: "100"
  PERSERVERCONNECTIONS: "25000"
  KEEPALIVETIMEOUT: "120"
  MAXKEEPALIVEREQUESTS: "1000"
  IMAGESTORETYPE: "mongodb"
  HTTPPORT: "80"
  HTTPSPORT: "443"
  APPSERVERS: "tomcat:8080"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      name: nginx
      labels:
        app: auction
        tier: backend
        type: webServer
        impl: nginx
    spec:
      containers:
      - image: hrosenbe/weathervane-nginx:1.1.0
        name: nginx
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: nginx-config
        ports: 
        - containerPort: 80
          name: httpport
          protocol: TCP
        - containerPort: 443
          name: httpsport
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    name: httpport
  - port: 443
    name: httpsport
  selector:
    app: auction
    tier: backend
    type: webServer
    impl: nginx