# Copyright (c) 2017 VMware, Inc. All Rights Reserved.
# 
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
# Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
# Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  labels:
    app: auction
    tier: backend
    type: coordinationServer
    impl: zookeeper
data: 
  ZK_CLIENT_PORT: "2181"
  ZK_PEER_PORT: "2888"
  ZK_ELECTION_PORT: "3888"
  ZK_SERVERS: "server.1=zookeeper-0.zookeeper:2888:3888,server.2=zookeeper-1.zookeeper:2888:3888,server.3=zookeeper-2.zookeeper:2888:3888"
  ZK_ID: "0"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: auction
    tier: backend
    type: coordinationServer
    impl: zookeeper
spec:
  serviceName: zookeeper
  selector:
    matchLabels:
      app: auction
      tier: backend
      type: coordinationServer
      impl: zookeeper
  replicas: 3
  template:
    metadata:
      name: zookeeper
      labels:
        app: auction
        tier: backend
        type: coordinationServer
        impl: zookeeper
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: wvrole
                operator: NotIn
                values:
                - driver
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: wvrole
                operator: In
                values:
                - sut
      containers:
      - image: repository/weathervane-zookeeper:1.2.0
        name: zookeeper
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: zookeeper-config
        ports: 
        - containerPort: 2181
          name: clientport
          protocol: TCP
        - containerPort: 2888
          name: peerport
          protocol: TCP
        - containerPort: 3888
          name: electionport
          protocol: TCP
        resources:
          requests:
            cpu: 1
            memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: auction
    tier: backend
    type: coordinationServer
    impl: zookeeper
spec:
  clusterIP: None
  ports:
  - port: 2181
    name: clientport
  - port: 2888
    name: peerport
  - port: 3888
    name: electionport
  selector:
    app: auction
    tier: backend
    type: coordinationServer
    impl: zookeeper