apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  labels:
    app: auction
    tier: backend
    type: coordinationServer
    impl: zookeeper
data: 
  ZK_CLIENT_PORT: "2181"
  ZK_PEER_PORT: "2888"
  ZK_ELECTION_PORT: "3888"
  ZK_SERVERS: "server.1=zookeeper-0.zookeeper:2888:3888,server.2=zookeeper-1.zookeeper:2888:3888,server.3=zookeeper-2.zookeeper:2888:3888"
  ZK_ID: "0"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: auction
    tier: backend
    type: coordinationServer
    impl: zookeeper
spec:
  serviceName: zookeeper
  selector:
    matchLabels:
      app: auction
      tier: backend
      type: coordinationServer
      impl: zookeeper
  replicas: 3
  template:
    metadata:
      name: zookeeper
      labels:
        app: auction
        tier: backend
        type: coordinationServer
        impl: zookeeper
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: wvrole
                operator: NotIn
                values:
                - driver
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: wvrole
                operator: In
                values:
                - sut
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: wvw1i1
                operator: Exists
      containers:
      - image: repository/weathervane-zookeeper:1.2.0
        name: zookeeper
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: zookeeper-config
        ports: 
        - containerPort: 2181
          name: clientport
          protocol: TCP
        - containerPort: 2888
          name: peerport
          protocol: TCP
        - containerPort: 3888
          name: electionport
          protocol: TCP
        resources:
          requests:
            cpu: 1
            memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: auction
    tier: backend
    type: coordinationServer
    impl: zookeeper
spec:
  clusterIP: None
  ports:
  - port: 2181
    name: clientport
  - port: 2888
    name: peerport
  - port: 3888
    name: electionport
  selector:
    app: auction
    tier: backend
    type: coordinationServer
    impl: zookeeper