/*
Copyright (c) 2017 VMware, Inc. All Rights Reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
auction.strings = {
	auction: 'Auction',
    auctionLogin : 'Auction Login',
    
    teaserHeader: 'Attend an active auction to join in the fun!',
    teaserText: 'Attend an auction from the list on the right, or search for an auction or item using the search tools available under Explore Auctions.',
    
	activeAuctions: 'Active Auctions',
	auctions: 'Auctions',
	allAuctions: 'All Auctions',
	searchAuctions: 'Search Auctions',
	searchItems: 'Search Items',
	upcomingAuctions: 'Upcoming Auctions',
	auctionId: 'Auction ID',
	auctionName: 'Name',
	dateStarted: 'Date Started',
	timeStarted: 'Time Started',
	startDate: 'Date',
	startTime: 'Start Time',
	auctionCategory: 'Category',
	auctionState: 'Status',
	attendAuctions: "Attend Auctions",
	exploreAuctions: "Explore Auctions",
	manageAuctions: "Manage Auctions",
	dashboard: "Dashboard",
	accountInfo: "Account Info",
	viewAuctionDetails: "View Details",
	viewAuctionDetailsSmall: "Details",
	joinAuction: "Attend Auction",
	joinAuctionSmall: "Attend",
	details: 'Details',
	join: 'Attend',
	items: 'Items',
	purchasedItems: 'Purchased Items',
	itemId: 'Item ID',
	itemName: 'Item Name',
	itemManufacturer: 'Manufacturer',
	itemDetail: 'Item Details',
	description: "Description",
	startingBid: "Starting Bid",
	dateOfOrigin: "Date of Manufacture",
	condition: "Condition",
	from: "From",
	to: "To",
	add: "Add",
	edit: "Edit",
	addImages: "Add Images",
	editItemLimitError: "Can only edit items that are not already sold.",
	image: "Image",
	
	itemState: 'Status',
	bidId: 'Bid Id',
	bidAmount: 'Current Bid',
	bidState: 'Bidding Status',
	auctionDetails: "Auction",
	adminTools: "Administrator Tools",
	backToBidding: "Return to Bidding",
	userState: 'Status',
	authorities: "Authorities",

	newCondition: "New",
	excellent: "Excellent",
	veryGood: "Very Good",
	good: "Good",
	fair: "Fair",
	poor: "Poor",
	bad: "Bad",
	details: "Details",
	
	addAuction: "Add Auction",
	myAuctions: "My Auctions",
	editAuction: "Edit Auction",
	addItem: "Add Item",
	myItems: "My Items",
	editItem: "Edit Item",
		
	auctionFUTURE: 'Scheduled',
	auctionPENDING: 'Starting Soon',
	auctionRUNNING: 'Active', 
	auctionCOMPLETE: 'Ended',
	auctionINVALID: 'Invalid',
	auctionNOSUCHAUCTION: 'Auction does not exist!',
	itemNOTLISTED: 'Item not listed',
	itemINAUCTION: 'In Auction',
	itemACTIVE: 'Up for bid',
	itemLASTCALL: 'Last Call for bids',
	itemSOLD: 'Sold',
	itemPAID: 'Paid',
	itemSHIPPED: 'Shipped',
	itemNOSUCHITEM: 'Item does not exist',
	bidOPEN: "Active",
	bidLASTCALL: "Last call for bids",
	bidSOLD: "Sold",
	bidINFO: "Info",
	bidAUCTIONCOMPLETE: "Auction Complete",
	bidAUCTIONNOTACTIVE: "Auction is not active",
	bidITEMNOTACTIVE: "Item is not available for bids",
	bidUNKNOWN: "Unknown",
	bidHIGHBIDDER: "You are currently the high bidder!",
	bidWINNINGBIDDER: "You are the winning bidder for this item!",
	
	bidMsg: "Bid Info",
	bidMsgHIGH: "Your bid was the high bid", 
	bidMsgWINNING: "Your bid was the winning bid", 
	bidMsgACCEPTED: "Your bid has been accepted", 
	bidMsgALREADYHIGHBIDDER: "Your bid was not accepted.\nYou are already the high bidder for this item.", 
	bidMsgAFTERHIGHER: "Your bid arrived after a higher bid", 
	bidMsgAFTERMATCHING: "Your bid arrived after a matching bid", 
	bidMsgBELOWSTARTING: "Your bid was below the starting bid", 
	bidMsgAUCTIONNOTRUNNING: "The auction is not active.", 
	bidMsgAUCTIONCOMPLETE: "The auction has already finished", 
	bidMsgITEMNOTAVAILABLE: "That item is not available for bids", 
	bidMsgITEMSOLD: "The item was already sold", 
	bidMsgINSUFFICIENTFUNDS: "You have insufficient fund to cover that bid", 
	bidMsgDUMMY: "This was a dummy bid", 
	bidMsgSTARTING: "This is the starting bid issued by the system",
	bidMsgBIDNOW: "Bid Now!",
	
	purchaseDate: "Purchase Date",
	purchasePrice: "Purchase Price",
	
	bidHistory: "Bid History",
	bidDate: "Bid Date",
	bidAmount: "Bid Amount",

	attendanceHistory: "Attendance History",
	attendanceDate: "Attendance Date",
	attendanceDuration: "Attendance Duration",
	attendanceAction: "Attendance Action",

	location : '3401 Hillview Ave Palo Alto, CA 94304 USA',
    warning : 'Warning!',
    profile : 'Profile',

    help : 'Help',
    logout : 'Logout',
    copyright : 'Copyright &copy; 2015 VMware, Inc. All rights reserved.',
    contactUs : 'Contact us',
    login : 'Login',
    pleaseLogin : 'Please enter your email-address and password to login.',
    enterUsername: 'Enter Email',
    email : 'Email',
    rememberMe : 'Remember me',
    password : 'Password',
    enterPassword : 'Enter Password',
    forgotPassword : 'Forgot password?',
    registration : 'Registration',
    dontHaveNanotrader : 'Don\'t have a Auction account yet?',
    createOneNow : 'Create one now!',
    pleaseRegister : 'Please Register me now',
    username : 'Email Address',
    invalidUser : 'Invaild Username and/or Password. Please try again.',
    unknownError : 'An unknown error has occurred. Please try again later.',

    accountId : 'Account ID',
    accountCreationDate : 'Account Creation Date',
    sessionExpired : 'Your session has expired. Please login in to continue.',

    registerUserName : 'Register New User',
    enterAccountDetails : 'Please enter your information in the form below',
    fullName : 'Full name',
    firstName : 'First name',
    lastName : 'Last name',
    passwordConfirmation : 'Password Confirmation',
    passwordMatching : 'Please make sure Password fields are matching',
    userId : 'User ID',
    creditCardNumber : 'Credit Card Number',
    creditLimit : 'Credit Limit',
    address : 'Address',
    register : 'Register',
    alreadyRegistered : 'If you have already registered, please enter your login and password on our login page.',
    visitLoginPage : 'Visit login page',
    emptyFieldError : 'Please complete all the registration fields.',
    newPassword : 'New Password',
    existingEmailError: 'There is already an account associated with that email address.',
    
    nearestLocation: 'Nearest VMware location',
    accountProfile : 'Account Profile',
    updateProfile : 'Update Account Profile',
    update : 'Update',
    name : 'Name',
    phone : 'Phone',
    message : 'Message',
    send : 'Send',
    ok : 'OK',
    cancel : 'Cancel',
    applicationOverview : 'Application Overview',    
    errorOcurred : 'An error has occurred.',
    anError : 'You received an error.',
    firstnameError : 'Please re-enter your First name.',
    lastnameError : 'Please re-enter your Last name.',
    emailError : 'Please re-enter your e-mail address.',
    passwdError : 'Error! You entered invalid characters into the password field. Please re-enter your password.', 
    usernameError : 'Please re-enter your username.',
    creditLimitError : 'Please re-enter your credit limit',
    addressError : 'Please re-enter your address',
    gainingMsg : 'This chart shows the top 4 gaining stocks in your portfolio',
    portfolioMsg : 'This chart shows the cash balance and the portfolio value as a % of the total assets in your account',
    loginPage : 'Login Page',
    enterNumUsers : 'Number of accounts to create',
    userdataHeadsUp : 'Warning! This will delete existing user accounts, associated data and recreate them (excluding admin user)',
    goToLoginPage : 'Go To Login Page',
};
