apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
data: 
  POSTGRES_USER: "auction"
  POSTGRES_PASSWORD: "auction"
  POSTGRESPORT: "5432"
  POSTGRESTOTALMEM: "16"
  POSTGRESTOTALMEMUNIT: "G"
  POSTGRESSHAREDBUFFERS: "0"
  POSTGRESSHAREDBUFFERSPCT: "0.25"
  POSTGRESEFFECTIVECACHESIZE: "0"
  POSTGRESEFFECTIVECACHESIZEPCT: "0.65"
  POSTGRESMAXCONNECTIONS: "0"
