apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
data: 
  ZK_CLIENT_PORT: "2181"
  ZK_PEER_PORT: "2888"
  ZK_ELECTION_PORT: "3888"
  ZK_SERVERS: "server.1=zookeeper-0:2888:3888"
  ZK_ID: "1"
