/* This script creates the schema for the Auction application
 *  when using MySQL.
 *
 * Last modified by: Hal Rosenberg
 */  

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

SHOW WARNINGS;

CREATE USER 'auction' identified by 'auction';
GRANT ALL ON *.* TO 'auction';

DROP SCHEMA IF EXISTS `auction` ;
CREATE SCHEMA IF NOT EXISTS `auction` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
